/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordmanager;

/**
 *
 * @author User
 */
public class PasswordManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form PasswordManagerGUI
     */
    public PasswordManagerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgrnd = new javax.swing.JPanel();
        TitleLBL = new javax.swing.JLabel();
        AddPasswordBTN = new javax.swing.JButton();
        RetrievePasswordBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayPasswordsTA = new javax.swing.JTextArea();
        LBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Backgrnd.setBackground(new java.awt.Color(204, 255, 255));

        TitleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleLBL.setText(" Password Manager ");
        TitleLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AddPasswordBTN.setBackground(new java.awt.Color(102, 255, 102));
        AddPasswordBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddPasswordBTN.setText("Add Password");
        AddPasswordBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPasswordBTNActionPerformed(evt);
            }
        });

        RetrievePasswordBTN.setBackground(new java.awt.Color(255, 204, 204));
        RetrievePasswordBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RetrievePasswordBTN.setText("Retrieve Password");
        RetrievePasswordBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrievePasswordBTNActionPerformed(evt);
            }
        });

        DisplayPasswordsTA.setColumns(20);
        DisplayPasswordsTA.setRows(5);
        jScrollPane1.setViewportView(DisplayPasswordsTA);

        LBL.setText("Saved Passwords: ");

        javax.swing.GroupLayout BackgrndLayout = new javax.swing.GroupLayout(Backgrnd);
        Backgrnd.setLayout(BackgrndLayout);
        BackgrndLayout.setHorizontalGroup(
            BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgrndLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(TitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgrndLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RetrievePasswordBTN)
                    .addComponent(AddPasswordBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        BackgrndLayout.setVerticalGroup(
            BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgrndLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgrndLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(AddPasswordBTN)
                        .addGap(35, 35, 35)
                        .addComponent(RetrievePasswordBTN))
                    .addGroup(BackgrndLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LBL)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPasswordBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPasswordBTNActionPerformed

    }//GEN-LAST:event_AddPasswordBTNActionPerformed

    private void RetrievePasswordBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrievePasswordBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetrievePasswordBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPasswordBTN;
    private javax.swing.JPanel Backgrnd;
    private javax.swing.JTextArea DisplayPasswordsTA;
    private javax.swing.JLabel LBL;
    private javax.swing.JButton RetrievePasswordBTN;
    private javax.swing.JLabel TitleLBL;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
